requires 'Mojolicious',    '>= 9.0';
requires 'DBI',            '>= 1.643';
requires 'DBD::mysql',     '>= 4.050';
requires 'JSON::XS',       '>= 4.0';
requires 'Try::Tiny',      '>= 0.30';
requires 'POSIX';
